#ifndef MMVIEWER_RESOURCE_H
#define MMVIEWER_RESOURCE_H

#define IDI_MMVIEWER 101
#define IDR_MERMAID_HTML 210
#define IDR_MERMAID_JS 211
#define IDR_MERMAID_LICENSE 212
#define IDR_WEBVIEW2_LICENSE 213
#define IDR_WEBVIEW2_NOTICE 214

#endif
